### ISSUE TITLE
Query SQL per un questionario

### ISSUE THREAD

**Issue by SimVac** [SimVac/questionari#10]
Scrivere la query sql per ottenere i dati di un singolo questionario

**Comment by MattiaCorradini** [comment]
SELECT titolo, descrizione FROM questionario WHERE id = :idQuestionario;

**Comment by MattiaCorradini** [comment]
SELECT titolo, descrizione FROM questionario WHERE id = :idQuestionario;

SELECT testo FROM domanda INNER JOIN questionario ON domanda.idQuestionario = questionario.id WHERE questionario.id = :idQuestionario ORDER BY ordine;

corretto
