### ISSUE TITLE
Aggiunta di un questionario

### ISSUE THREAD

**Issue by SimVac** [SimVac/questionari#11]
Implementare l'aggiunta di un questionario. Necessario essere admin

**Comment by SimVac** [comment]
Pensavo di far passare in json i dati delle domande come array e inviarli come POST. Per farlo bisogna usare nell'html e javascript il preventDefault o una roba del genere e riscrivere l'evento che farà il fetch POST verso il server. Ci sarà bisogno quindi che nel javascript ci sia un modo di ottenere i dati compilati dall'utente

**Comment by SimVac** [comment]
con la commit 952a1eb22bb574a8b0fba269115e6d8ec082ede6 crea lo scheletro dell'aggiunta, mancano le query

**Comment by MattiaCorradini** [comment]
INSERT INTO questionario (titolo, descrizione) VALUES (:titolo, :descrizione);

INSERT INTO domanda (ordine, testo, idQuestionario) VALUES (:ordine, :testo, :idQuestionario);

**Comment by SimVac** [comment]
completa #36
