### ISSUE TITLE
Bug nella navigazione dalla pagina login alla pagina di registrazione

### ISSUE THREAD

**Issue by SimVac** [SimVac/questionari#45]
Modificare il tag a contenente come href solo "index.php?action=registrazione". Altrimenti per come è ora va sempre alla root/index.php

**Comment by ScarsatoAndrea** [comment]
quale tag a???? e poi se è una stronzata del genere correggila te no? dc

**Comment by SimVac** [comment]
ma fra è sul tuo branch frontend, era per non toccarlo io

**Comment by ScarsatoAndrea** [comment]
sta zitto coglione che io tocco tua sorella altro che il tuo branch

**Comment by SimVac** [comment]
che poi mi rompi il cazzo che ci sono conflitti

**Comment by ScarsatoAndrea** [comment]
guarda che il mio branch non è l'area 51, puoi farlo uno switch e togliere uno / senza creare un issue

**Comment by SimVac** [comment]
ora sono nel mio letto
