### ISSUE TITLE
Invio mail

### ISSUE THREAD

**Issue by ScarsatoAndrea** [SimVac/questionari#50]
Inserisco una mail valida in registrazione ma lancia un'eccezione dicendo che non è valida
Invalid address: (From):

Fatal error: Uncaught PHPMailer\PHPMailer\Exception: Invalid address: (From): in C:\Users\andre\Downloads\xampp-portable-windows-x64-8.0.10-0-VS16\xampp\htdocs\vendor\phpmailer\phpmailer\src\PHPMailer.php:1331 Stack trace: #0 C:\Users\andre\Downloads\xampp-portable-windows-x64-8.0.10-0-VS16\xampp\htdocs\Util\Email.php(28): PHPMailer\PHPMailer\PHPMailer->setFrom('') #1 C:\Users\andre\Downloads\xampp-portable-windows-x64-8.0.10-0-VS16\xampp\htdocs\index.php(55): Util\Email->sendEmail('andrea25030@gma...', 'QuestionAPP reg...', 'Thank you for t...') #2 {main} thrown in C:\Users\andre\Downloads\xampp-portable-windows-x64-8.0.10-0-VS16\xampp\htdocs\vendor\phpmailer\phpmailer\src\PHPMailer.php on line 1331

**Comment by ScarsatoAndrea** [comment]
var dump di post
array(7) { ["registrazione"]=> string(4) "true" ["nome"]=> string(6) "Andrea" ["cognome"]=> string(8) "Scarsato" ["mail"]=> string(21) "andrea25030@gmail.com" ["password"]=> string(3) "asd" ["password_confirmation"]=> string(5) "asdfa" ["marketing_accept"]=> string(2) "on" }

**Comment by SimVac** [comment]
hai configurato correttamente il config.php?

**Comment by ScarsatoAndrea** [comment]
wtf ieri l'avevo fatto, va be faccio ora
