### ISSUE TITLE
Query SQL per la visualizzazione dei questionari

### ISSUE THREAD

**Issue by SimVac** [SimVac/questionari#9]
Scrivere la query sql per visualizzare i dati che saranno presenti nella pagina di visualizzazione dei questionari

**Comment by SimVac** [comment]
Quando scrivi una query mettila come commento qui e chiudi l'issue

**Comment by MattiaCorradini** [comment]
SELECT titolo, descrizione FROM questionario;

**Comment by MattiaCorradini** [comment]
errato ma chiudo
